### ISSUE TITLE
Not able to create UserGroup & Users

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterPrefabs/UserAdmin#47]
SC Version 2.3.0.5282

Handler `http://localhost:8080/UserAdmin/admin/usergroups`
Button `Create UserGroup`

is giving an exception on the page : 
![image](https://cloud.githubusercontent.com/assets/4388707/21047348/b72827b2-be09-11e6-8747-cd8a766fb763.png)

The error in SC Log is :
```
System.TypeInitializationException: The type initializer for 'UserAdmin.CreateUserGroupPage' threw an exception.
   at UserAdmin.CreateUserGroupPage..ctor()
   at UserAdmin.SystemUserGroupsHandlers.<>c.<Register>b__0_0(Request request) in E:\Development\StarCounter\UserAdmin\src\UserAdmin\Api\SystemUserGroupsHandlers.cs:line 21
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-363\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
TypeName=UserAdmin.CreateUserGroupPage
HResult=-2146233036
---> System.MissingMethodException: Method not found: 'Void Starcounter.Templates.Template.set_ClassName(System.String)'.
   at Smorgasbord.PropertyMetadata.PropertyMetadataPage.JsonByExample.Schema..ctor()
   at UserAdmin.CreateUserGroupPage.JsonByExample.Schema..ctor()
   at UserAdmin.CreateUserGroupPage..cctor()
HResult=-2146233069

```

**Comment by miyconst** [comment]
@atifwaqar this is the same problem with compatibility.

You have to clone the [PropertyMetadataPage](https://github.com/Smorgasbord-Development/PropertyMetadata/) repository and reference it from UserAdmin, instead of using the NuGet package.

**Comment by atifwaqar** [comment]
Awesome. It works now. Thank you :)

**Comment by warpech** [comment]
We should release a new version. PropertyMetadata has been included in UserAdmin `develop` branch (https://github.com/StarcounterPrefabs/UserAdmin/commit/3ac86a4b48d91b9296ddc3842081d91c8488f34c).
